//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChapooModel
{
    using System;
    using System.Collections.Generic;
    
    public  class Bestel_Gerecht
    {
        public int bestelling_ID { get; set; }
        public int gerecht_ID { get; set; }
        public int werknemer_ID { get; set; }
        public Nullable<int> status { get; set; }
        public string commentaar { get; set; }
        public int aantal { get; set; }
    }
}
