//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChapooModel
{
    using ChapooModel.Models;
    using System;
    using System.Collections.Generic;
    
    public partial class Bestelling
    {

        public Inlog werknemer { get; set; }
        public int bestelling_ID { get; set; }
        public Tafel tafel { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public string commentaar { get; set; }
        public bool betaald { get; set; }
        public List<OrderItem> orderItems { get; set; }
    }
}
