//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChapooModel
{
    using System;
    using System.Collections.Generic;
    
    public class Inlog
    {
        public int werknemer_ID { get; set; }
        public string naam { get; set; }
        public string wachtwoord { get; set; }
        public string functie { get; set; }
    }
}
