//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChapooModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tafel
    {
    
        public int tafel_id { get; set; }
        public Nullable<bool> bezet { get; set; }
        public virtual ICollection<Bestelling> Bestelling { get; set; }
    }
}
